server:
  port: 80
  max-http-header-size: 8000KB

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
      id-type: auto

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssm_db?serverTimezone=UTC
      username: root
      password: jw20120324
#ehcache
#  cache:
#    type: ehcache
#    ehcache:
#      config: classpath:ehcache.xml
  cache:
    type: redis
    redis:
#      use-key-prefix: false
#      cache-null-values: false
      key-prefix: sms_
      time-to-live: 10s
  redis:
    host: localhost
    port: 6379



