server:
  port: 81

spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:8080
        instance:
          management-base-url: http://localhost:81

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

