server:
  port: 80

#debug: true
logging:
  level:
    root: info
    # 设置某个包的日志级别
#    com.jiang.controller: debug
    ebank: warn
  group:
    ebank: com.jiang.controller,com.jiang.service,com.jiang.dao
    iservice: com.alibaba

  # 设置日志模版格式
  pattern:
    # console: "%d - %m %n"
    console: "%d %clr(%5p) --- [%16t] %clr(%-40.40c){cyan} : %m %n"
  file:
    name: server.log
  logback:
    rollingpolicy:
      max-file-size: 4KB
      file-name-pattern: server.%d{yyyy-MM-dd}.%i.log
